import Head from "next/head";
import { Inter } from "next/font/google";
import BasicSample from "./basic-sample";
import AdaptedProps from "./adapted-props";
import { TitleType } from "./adapted-props/adaptedPropsType";
import StyledComponent from "./styled-component/styledComponent";
import PseudoAndNesting from "./PseudoAndNesting/PseudoAndNesting";

export default function Home() {
  const adaptedPropData: TitleType = { color: "#ff0000" };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BasicSample />
        <AdaptedProps color={adaptedPropData.color} />
        <StyledComponent />
        <PseudoAndNesting />
      </main>
    </>
  );
}
